version: '3'

services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hbgworks
      - MYSQL_DATABASE=hbgworks_db
      - MYSQL_USER=hbgworks_user
      - MYSQL_PASSWORD=hbgworks_pw

  notifications-mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    volumes:
      - notifications-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=notifications
      - MYSQL_DATABASE=notifications_db
      - MYSQL_USER=notifications_user
      - MYSQL_PASSWORD=notifications_pw

  services-mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    volumes:
      - services-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=services
      - MYSQL_DATABASE=services_db
      - MYSQL_USER=services_user
      - MYSQL_PASSWORD=services_pw

  labs-node-js-boilerplate:
    image: labs-node-js-boilerplate
    build: https://github.com/helsingborg-stad/labs-node-js-boilerplate.git
    hostname: labs-node-js-boilerplate
    ports:
    - 3000:3000
    restart: unless-stopped
    environment:
      - SERVER_PORT=3000
      - LOG_LEVEL=info
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=hbgworks_db
      - MYSQL_CONNECTION_LIMIT=10
      - MYSQL_USER=hbgworks_user
      - MYSQL_PASSWORD=hbgworks_pw
    depends_on:
      - mysql
    command: sh -c './wait-for mysql:3306 -- npm run migrate:latest && npm start'

  labs-api-notification:
    image: labs-api-notification
    build: https://github.com/helsingborg-stad/labs-api-notification.git
    hostname: labs-api-notification
    ports:
    - 3001:3001
    restart: unless-stopped
    environment:
      - SERVER_PORT=3001
      - LOG_LEVEL=info
      - MYSQL_HOST=notifications-mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=notifications_db
      - MYSQL_CONNECTION_LIMIT=10
      - MYSQL_USER=notifications_user
      - MYSQL_PASSWORD=notifications_pw
    depends_on:
      - notifications-mysql
    command: sh -c './wait-for notifications-mysql:3306 -- npm run migrate:latest && npm start'

volumes:
  mysql-vol:
  notifications-vol:
  services-vol: