version: '3'

services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hbgworks
      - MYSQL_DATABASE=hbgworks_db
      - MYSQL_USER=hbgworks_user
      - MYSQL_PASSWORD=hbgworks_pw

  labs-node-js-boilerplate:
    image: labs-node-js-boilerplate
    build: https://github.com/helsingborg-stad/labs-node-js-boilerplate.git
    hostname: labs-node-js-boilerplate
    ports:
    - 3000:3000
    restart: unless-stopped
    environment:
      - PORT=3000
      - LOG_LEVEL=info

  labs-api-notification:
    image: labs-api-notification
    build: https://github.com/helsingborg-stad/labs-api-notification.git
    hostname: labs-api-notification
    ports:
    - 3001:3001
    restart: unless-stopped
    environment:
      - PORT=3001
      - LOG_LEVEL=info

volumes:
  mysql-vol: